all: clean
	cd step1; make all
	cd step2; make all
	cd step3; make all
	cd step4; make all
	cd step5; make all
	cd step6; make all
	cd step7; make all
	cd step8; make all
clean:
	cd step1; make clean
	cd step2; make clean
	cd step3; make clean
	cd step4; make clean
	cd step5; make clean
	cd step6; make clean
	cd step7; make clean
	cd step8; make clean
